[project]
name = "lzim-bot"
version = "0.1.0"
description = "Bot Discord - Lzim v9"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "discord.py>=2.3.2",
    "python-dotenv>=1.0.0",
    "pytz",
    "aiohttp",
    "requests",
    "yt-dlp"
]

[tool.uv]
dev-dependencies = []
